- template.yaml
Adjust image id placeholder so it can function correctly with github actions. 
Removed hard coded ECR image id value and replaced it with 'CONTAINER-IMAGE-PLACEHOLDER' which can now be referenced by workflow file.
- [F2F-128](https://govukverify.atlassian.net/browse/F2F-128)
[F2F-128]: https://govukverify.atlassian.net/browse/F2F-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-128]: https://govukverify.atlassian.net/browse/F2F-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-128a: Removed hard coded image value

- template.yaml
Adjusting APIGatewayId to remove circular referencing which is preventing us from updating and deleting stacks. 
Adjusted APIGatewayId import value so that it wasn't identical to the export value. 
- [F2F-128](https://govukverify.atlassian.net/browse/F2F-128)
[F2F-128]: https://govukverify.atlassian.net/browse/F2F-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-128]: https://govukverify.atlassian.net/browse/F2F-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-128a Removing circular reference of export

- .github/workflows/post-merge-actions-build.yml
Changed artifact bucket name back to 'ARTIFACT_BUCKET'
Was previously build specific but resulted in error due to incorrect bucket name.
> F2F-128d: Ajusted artifact bucket name.

- template.yaml
Docker image was previously hardcoded for dev as "060113405249.dkr.ecr.eu-west-2.amazonaws.com/di-cic-front:2", removed this value to instead populate with 'CONTAINER-IMAGE-PLACEHOLDER' so that the latest built docker image will also be deployed to the dev environment.
So that the latest built docker image will also be deployed to the dev environment.
- [PLAT-510](https://govukverify.atlassian.net/browse/PLAT-510)
[PLAT-510]: https://govukverify.atlassian.net/browse/PLAT-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-510b:Removed hardcoded image value

- template.yaml
Changed the APIGatewayId (for the backend) to the private export: "di-ipv-cri-cic-PrivateCICApiGatewayId"
Was previously public gateway id export.
> F2F-510c:Changed APIGatewayId to private export.

- template.yaml
Removed the WAF/ Load Balancer association resource 
This resource was causing a 403 error when trying to access our CIC CRI through the IPV Core stub due to the length of the url, removal of this resource removes the limit on the length of the url. 
- [F2F-231](https://govukverify.atlassian.net/browse/F2F-231)
[F2F-231]: https://govukverify.atlassian.net/browse/F2F-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-231: Removed WAFv2 LoadBalancer association as this is causing a 403 error.

- test/browser/features/BrowserBasedTests/UnHappyPath/InlineValidation/CICNameEntryScreenMissValue.feature
- test/browser/pages/nameEntryPage.js
- test/browser/step_definitions/CICNameEntryMissValue.step.js
- [F2F-354](https://govukverify.atlassian.net/browse/F2F-354)
[F2F-354]: https://govukverify.atlassian.net/browse/F2F-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-354 Name Entry missing value test

- src/app/cic/steps.js
This fixes the bug in [F2F-342](https://govukverify.atlassian.net/browse/F2F-342) which allowed past dates to be entered for the EU Driving Licence
- [F2F-342](https://govukverify.atlassian.net/browse/F2F-342)
[F2F-342]: https://govukverify.atlassian.net/browse/F2F-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-342]: https://govukverify.atlassian.net/browse/F2F-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-342] Fixes validation for past dates for EU Driving Licence

- src/app/cic/steps.js
Fixes the Non-UK Passport upper limit, changing to 75 years in the future as per [F2F-341](https://govukverify.atlassian.net/browse/F2F-341)
The upper limit was the incorrect value
- [F2F-341](https://govukverify.atlassian.net/browse/F2F-341)
[F2F-341]: https://govukverify.atlassian.net/browse/F2F-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-341]: https://govukverify.atlassian.net/browse/F2F-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-341] Updates Non-UK Passport upper limit to 75 years

- src/app/cic/steps.js
Updates the link for the the 'I do not have any of these documents' radio button on the document selection screen as per  [F2F-343](https://govukverify.atlassian.net/browse/F2F-343)
The link wasn't working correctly before
- [F2F-343](https://govukverify.atlassian.net/browse/F2F-343)
[F2F-343]: https://govukverify.atlassian.net/browse/F2F-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-343]: https://govukverify.atlassian.net/browse/F2F-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-343] Fixes 'I do not have any of these documents' link

- template.yaml
add AWS::StackName to FE APIGW description in DEV
make it easier to identify specific APIGWs in DEV env when looking at the AWS console
- [F2F-595](https://govukverify.atlassian.net/browse/F2F-595)
[F2F-595]: https://govukverify.atlassian.net/browse/F2F-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-595 add AWS::StackName to FE APIGW description in DEV

- README.md
- template.yaml
Configure the ECS autoscaling policies as described in ticket in order to ensure correct scaling under load.
During a load test in w/c 8th May it was found the FE did not scale properly under load.
- [F2F-602](https://govukverify.atlassian.net/browse/F2F-602)
[F2F-602]: https://govukverify.atlassian.net/browse/F2F-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-602 configure autoscaling policies for FE

- template.yaml
add responseLatency and integrationLatency to FE APIGW Access Log
assist in reviewing performance test results
- [F2F-659](https://govukverify.atlassian.net/browse/F2F-659)
[F2F-659]: https://govukverify.atlassian.net/browse/F2F-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-659 add responseLatency and integrationLatency to FE APIGW Access Log

- template.yaml
- Added alarms based on [this documentation](https://govukverify.atlassian.net/wiki/spaces/FTFCRI/pages/3602382964/CIC+BE+Metrics+Alerts#Back-End-Latency)
- Added start of CloudWatch Dashboard
- [F2F-425](https://govukverify.atlassian.net/browse/F2F-425)
[F2F-425]: https://govukverify.atlassian.net/browse/F2F-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Implement Monitoring & Alerts for CIC Frontend

- test/browser/support/shared_claim.json
CIC UI tests are failing as the shared claim body has incorrectly had the "target" field committed 
To enable the CIC UI tests to run in the pipeline
- [F2F-965](https://govukverify.atlassian.net/browse/F2F-965)
[F2F-965]: https://govukverify.atlassian.net/browse/F2F-965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> browsertests bug fix, shared claim body update

- template.yaml
Create a metric filter for FE APIGW & ECS if log message contains level is FATAL or message has Exception Unhandled
Create a cloud watch alarm if the log group finds the metric filter
Stack notification is sent if the alarm is triggered
tested manually writing a Fatal error log on the log messages
- [F2F-1017](https://govukverify.atlassian.net/browse/F2F-1017)
[F2F-1017]: https://govukverify.atlassian.net/browse/F2F-1017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-1017: Create alerting for fatal errors in FE and BE

- .gitignore
- Modified the github workflow test coverage pattern.
- [F2F-1117](https://govukverify.atlassian.net/browse/F2F-1117)
[F2F-1117]: https://govukverify.atlassian.net/browse/F2F-1117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-1117: cri-cic-front repository does not report coverage

- template.yaml
TESTHARNESS definition in build main template
was previously incorrect causing the test-container in build to fail and the pipeline to be blocked
- [F2F-1135](https://govukverify.atlassian.net/browse/F2F-1135)
[F2F-1135]: https://govukverify.atlassian.net/browse/F2F-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-1135 Update TESTHARNESS in BUILD main template

- .github/CODEOWNERS
- .github/pull_request_template.md
- Add the CODEOWNERS for new govuk-one-login github CIC Front
- [F2F-1320](https://govukverify.atlassian.net/browse/F2F-1320)
> KIWI-1320: Github Migrations - Post cleanup for CIC Front

- src/app.js
- src/app/cic/steps.js
- src/views/cic/error.html
- yarn.lock
Adds check for redirect_uri before performing a callback() to IPVCore, if redirect_uri is not present then an internal F2F Error page is shown allowing the user to navigate back to Gov.uk and begin their journey again
https://govukverify.atlassian.net/browse/KIWI-1297
**Before Fix**
**After Fix**
> [KIWI-1340] - Redirecting with server_error for Users not from IPV Core

- src/locales/cy/pages.yml
- src/locales/en/default.yml
- src/locales/en/pages.errors.yml
- src/locales/en/pages.yml
Any references to “[GOV.UK](http://gov.uk/) account” should be replaced with “[GOV.UK](http://gov.uk/) One Login”
The page with title Prove your identity in person is no longer required and should be removed. It has likely been superseded by the [landing page](https://www.figma.com/file/tK7chtvE4bSaWSmBU7zcLV/F2F-Flow---Screen-Iterations?type=design&node-id=6171-286110&mode=design&t=wHeTOuF0PbHMRKy3-4) that is now part of the F2F CRI
https://govukverify.atlassian.net/browse/KIWI-1170
> [KIWI-1170] - Update Copy to Fix Page Title Errors

- src/locales/cy/default.yml
- src/locales/cy/pages.errors.yml
- src/locales/en/default.yml
- src/locales/en/pages.errors.yml
- src/views/cic/error.html
- src/views/errors/error.html
Updates support link
There is a new contact centre URL
- [KIWI-1152](https://govukverify.atlassian.net/browse/KIWI-1152)
[KIWI-1152]: https://govukverify.atlassian.net/browse/KIWI-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1152] Updates support link

- package.json
- run-tests-locally.sh
- test/browser/support/TestHarness.js
Adds required `customCredentialsProvider` for sigv4
To fix end to end tests
> Gets sigv4 working

- .secrets.baseline
- src/app/cic/fields.js
Removed Date constructor in field validation logic
Date functions in fields.js are only instantiated when the JS is first created and then pulled in as static value in all future checks - i.e. deployment date. Removed the function in the before / after checks, as those functions then provide their own via Moment.js’ default constructor - see here https://github.com/HMPO/hmpo-form-wizard/blob/a45c5d5207334380fab9e89c34dced46db0aef1f/lib/validation/validators.js#L114
- [KIWI-1208](https://govukverify.atlassian.net/browse/KIWI-1208)
Before fix
After fix
[KIWI-1208]: https://govukverify.atlassian.net/browse/KIWI-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1208] - CIC & F2F | Investigate whether Form Wizard is validating dates correctly

- src/app/cic/controllers/journeyType.js
- src/app/cic/controllers/journeyType.test.ts
- src/app/cic/controllers/root.js
- src/app/cic/controllers/root.test.js
- src/app/cic/steps.js
split journey type route into its own
root controller was causing infinite loop
- [KIWI-1568](https://govukverify.atlassian.net/browse/KIWI-1568)
[KIWI-1568]: https://govukverify.atlassian.net/browse/KIWI-1568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1568: split journey type route into its own

- src/locales/cy/default.yml
- src/locales/en/default.yml
Added empty quote in English and Welsh default yaml files to remove error showing govuk.serviceName in screen title tag
Bug fix
- [KIWI-1664](https://govukverify.atlassian.net/browse/KIWI-1664)
[KIWI-1664]: https://govukverify.atlassian.net/browse/KIWI-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1664]-CIC | FE | Incorrect tab title on all pages

- .secrets.baseline
- template.yaml
Alarm description on the front end does not hold the support manual url. Add the support manual url to the alarm description and point to the FE Metrics page. 
- Add Support Manual URL and point to the FE Metrics pages https://govukverify.atlassian.net/wiki/spaces/FTFCRI/pages/3623354496/CIC+FE+Metrics+Alerts
- Add Support manual description to Alarm descriptions
To include the support url on the alarms
- [KIWI-1603](https://govukverify.atlassian.net/browse/KIWI-1603)
[KIWI-1603]: https://govukverify.atlassian.net/browse/KIWI-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1668: Add Support Manual URL pointing to FE Metrics Page

- .secrets.baseline
- template.yaml
Alarms are created on dev for every custom stack created on the dev account. 
In order to optimise the stack, alarm is set to off by default 
Change the flag to deploy on dev set to false.
Added the condition on metric filter and alarms
Modified the concurrency alarms flag.
Too many alarms created when a new custom is created.
- [KIWI-1717](https://govukverify.atlassian.net/browse/KIWI-1717)
- [IPS-678](https://govukverify.atlassian.net/browse/IPS-678)
[KIWI-1717]: https://govukverify.atlassian.net/browse/KIWI-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-678]: https://govukverify.atlassian.net/browse/IPS-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1717: Set Alarms to Off by Default in Dev

- package.json
- yarn.lock
Bumps common express from 6.2.0 to 6.2.2
The recent GA4 package release had to be updated in common-express as well. Bumping this version will produce cleaner logs
> BAU: Bump @govuk-one-login/di-ipv-cri-common-express from 6.2.0 to 6.2.2

- src/locales/cy/default.yml
- src/locales/cy/pages.errors.yml
- src/views/cic/enter-name.html
- Remove backslashes from welsh content
- Update HTML on name page use fieldsets (matches passport CRI)
- Moves closing div to make sure that container holds whole page not just title
To make CIC more accessible 
- [KIWI-1808](https://govukverify.atlassian.net/browse/KIWI-1808)
[KIWI-1808]: https://govukverify.atlassian.net/browse/KIWI-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1808 a11y fixes

- src/views/cic/enter-name.html
Changed the page title for no photo id (bank account) journey to match the H1 
To align with the requested DAC report changes and provide screen readers with immediate instructions for what to do on the page 
- [KIWI-1411](https://govukverify.atlassian.net/browse/KIWI-1411)
[KIWI-1411]: https://govukverify.atlassian.net/browse/KIWI-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1411] - BAV | NFR | Implement changes from DAC review

- src/views/cic/confirm-details.html
Add missing analytics attributes to button
Navigation data layer push, specifically the Inbound Button is not firing on one of the CIC CRI pages [www.review-c.account.gov.uk/confirm-details](http://www.review-c.account.gov.uk/confirm-details)
- [DFC-602](https://govukverify.atlassian.net/browse/DFC-602)
[DFC-602]: https://govukverify.atlassian.net/browse/DFC-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DFC-602: Add missing analytics attributes to button

- .secrets.baseline
- template.yaml
IPS-732: Change DNS Records link to the cloudfront distribution
- This should link dns to cloudfront in CIC dev and build
- This should disable the existing WAF association in all environments other than prod.
Once this has been verified / proven to be working the the dns link will be increased to integration.
Fixed the deployment template - sorted out all of the cloudformation linting warnings / errors - put exceptions where necessary so that it lints correctly
modified:   .secrets.baseline
modified:   template.yaml
- [IPS-732](https://govukverify.atlassian.net/browse/IPS-732)
[IPS-732]: https://govukverify.atlassian.net/browse/IPS-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-732: Change DNS Records link to the cloudfront distribution

- test/browser/support/CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json
- test/browser/support/CIC_CRI_START_SCHEMA.json
Update following TxMA JSON Schema to check for `restricted.device_information` field
- CIC_CRI_START_SCHEMA.json
- CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json
Support testing of CloudFront changes
- [KIWI-1868](https://govukverify.atlassian.net/browse/KIWI-1868)
[KIWI-1868]: https://govukverify.atlassian.net/browse/KIWI-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1868 - Cloudfront Header Updates

- sonar-project.properties
- src/app/cic/controllers/journeyType.test.js
- src/app/cic/fields.js
Update sonar properties and fix unit tests for `journeyType` controller in CIC
To increase code coverage
- [KIWI-1895](https://govukverify.atlassian.net/browse/KIWI-1895)
CIC sonar scan passing coverage threshold locally
[KIWI-1895]: https://govukverify.atlassian.net/browse/KIWI-1895?
atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI -1895] - CIC & IPR | Fe | Investigate drop in sonar Kiwi FE code coverage

- src/app/cic/steps.js
- src/locales/cy/pages.yml
- src/locales/en/pages.yml
- src/views/cic/confirm-details-hmrc-check.html
- src/views/cic/confirm-details-no-photo-id.html
- src/views/cic/enter-date-birth-hmrc-check.html
- src/views/cic/enter-name-hmrc-check.html
- src/views/cic/enter-name.html
- Create a new Name Entry screen specific to the Low Confidence Journey
- Create a new dateOfBirth screen specific to the Low Confidence Journey
- Create a new checkYourDetails screen specific to the Low Confidence Journey
- Add conditional routing to the CIC root controller and journey steps file to direct users to the correct sequence of screens depending on the CIC use case
- Fix Low_Confidence & noPID routing issues 
- Add Welsh copy for the new screens
> [KIWI-1942] Implement Low Confidence Journey with New Screens and Conditional Routing

- src/locales/cy/pages.yml
- src/views/cic/confirm-details-hmrc-check.html
- src/views/cic/confirm-details-no-photo-id.html
- src/views/cic/confirm-details.html
- src/views/cic/enter-date-birth-hmrc-check.html
- src/views/cic/enter-date-birth-no-photo-id.html
- src/views/cic/enter-date-birth.html
Removed journey type from hmpoPageKey as this was preventing DOB and check details pages accessing the copy in the yaml files. This copy in particular was not conditional based on journey type so the suffixes weren't necessary
To show the page title correctly on browser tabs
- [KIWI-1986](https://govukverify.atlassian.net/browse/KIWI-1986)
[KIWI-1986]: https://govukverify.atlassian.net/browse/KIWI-1986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1986 CIC | FE | Incorrect Page Titles in Staging

- src/app/cic/fields.js
- src/app/cic/fields.test.js
[KIWI-2029] Add Max Length validation to fields
[KIWI-2029]: https://govukverify.atlassian.net/browse/KIWI-2029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2029] Add Max Length validation to fields

- package.json
- yarn.lock
Updated Express dependency
Updated Express dependency to 4.21.2
To address vulnerabilities
> Dependabot: Express update

- .secrets.baseline
- template.yaml
This is protected by a specific WAF for CloudFront
Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
Added tags
to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
https://govukverify.atlassian.net/browse/IPS-1407
> Update to  exclude the origin load balancer from the regional FMS policy

- src/lib/locals.js
- [KIWI-2172](https://govukverify.atlassian.net/browse/KIWI-2172)
[KIWI-2172]: https://govukverify.atlassian.net/browse/KIWI-2172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2172] - fix to incorrect GA4 naming

- .github/workflows/pre-merge-checks.yml
Bumped the GH Action to use the new SonarCloud GH Action
Upstream action deprecated
- [IPS-1428](https://govukverify.atlassian.net/browse/IPS-1428)
- No changes
[IPS-1428]: https://govukverify.atlassian.net/browse/IPS-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1428 update sonarcloud version before march deadline

- src/app.js
- src/lib/config.js
- template.yaml
Added name to hmpo-logger.get() function to prevent use of sync API which blocks event loop
Prevent blocking functions from impacting performance
- [KIWI-2012](https://govukverify.atlassian.net/browse/KIWI-2012)
[KIWI-2012]: https://govukverify.atlassian.net/browse/KIWI-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2012] -  | CM | Remove blocking from node eventloop 

- package.json
- src/app.js
- src/app/cic/fields.test.js
- src/lib/config.js
- src/views/cic/enter-date-birth-hmrc-check.html
- src/views/cic/enter-date-birth-no-photo-id.html
- src/views/cic/enter-date-birth.html
- src/views/cic/enter-name-hmrc-check.html
- src/views/cic/enter-name-no-photo-id.html
- src/views/cic/enter-name.html
- yarn.lock
Upgraded frontend-analytics package version and added missing data attributes used for GA4 navigation tracking
To ensure service is up to date and capturing analytics data correctly
- [KIWI-2216](https://govukverify.atlassian.net/browse/KIWI-2216)
https://github.com/user-attachments/assets/e5a8e03e-8024-4579-b0ca-2aee5f4d9314
[KIWI-2216]: https://govukverify.atlassian.net/browse/KIWI-2216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2216] Upgrade FE analytics from v 2.0.1 to 3.1.0

- package.json
- src/app.js
- src/lib/overload-protection-config.js
Implemented overload protection to return 503s from the FE when event loop delay exceeds threshold indicating node app is overloaded
> KIWI-2010 - Implementing oveload protection

- .secrets.baseline
- template.yaml
Replaced existing ECS autoscaling policy with step scale-in and scale-out policies, with alarms
To meet requirement of ADR 140 and scale more effectively for our use cases in KIWI
https://github.com/govuk-one-login/architecture/blob/main/adr/0140-fargate-scaling.md
- [KIWI-2244](https://govukverify.atlassian.net/browse/KIWI-2244)
[KIWI-2244]: https://govukverify.atlassian.net/browse/KIWI-2244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2244] - KIWI | CM | Aligning Auto-Scaling Policies with ADR 140

- package.json
- yarn.lock
Updated common-express package to latest version which includes fix for device intelligence feature toggle.
- [KIWI-2250](https://govukverify.atlassian.net/browse/KIWI-2250)
[KIWI-2250]: https://govukverify.atlassian.net/browse/KIWI-2250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2250 - Bump common-express version

- .github/workflows/pre-merge-checks.yml
- package.json
- test/browser/features/BrowserBasedTests/UnHappyPath/Cookies/CICCookies.feature
- test/browser/pages/nameEntryPage.js
- test/browser/step_definitions/details.js
Add Unhappy Path test for Device Intelligence cookies
Ensure feature flag is working as expected and no device_intelligence cookies are present when flag is set to false
> Device intelligence unhappy path

- test/browser/features/BrowserBasedTests/HappyPath/CICCookies.feature
Disabled DI browser tests from pipeline
This is in line with the choice made with other Kiwi CRI's that browser tests that attempt to validate cookie presence should not run in the pipeline as they currently fail for unknown reasons - tech debt will be raised to investigate.
> Pipeline fix - Disabled DI browser tests from pipeline

- test/browser/step_definitions/details.js
Small fix for DI cookie browser test by adding a wait time to the test
The assumption is that this test was failing in the pipeline due to the test running before the page had finished loading, therefore the expected cookie was not present.
> Small fix for DI cookie browser test

- template.yaml
Turned on Device Intelligence in staging, integration and production
To enable the program to collect collection and analysis of data from end user devices and satisfy HMRC Day2 Must Have requirements
- [KIWI-2251](https://govukverify.atlassian.net/browse/KIWI-2251)
[KIWI-2251]: https://govukverify.atlassian.net/browse/KIWI-2251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2251] - | FE | Enable feature flag for Device Intelligence in INT and PROD

- package.json
- yarn.lock
Upgraded frontend-ui to 1.3.9 and upgraded govuk-frontend to 4.10.1
To fix issue of computed font size of text in the footer is smaller than the 16px minimum, and fix incorrect peer dependency
- [KIWI-2409](https://govukverify.atlassian.net/browse/KIWI-2409)
[KIWI-2409]: https://govukverify.atlassian.net/browse/KIWI-2409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI 2409] - CIC | FE | Computed font size of footer smaller than minimum 16px
