govuk-one-login/ipv-cri-cic-front

template.yaml, wafv2_template.yaml
[Ticket link ](https://govukverify.atlassian.net/browse/F2F-92)
Adding WAF as in in [DCMAW](https://github.com/alphagov/di-ipv-dca-infra/blob/main/platform-security/template.yml)
Tested by deploying on Dev environment and sending request to the API gateway with no `User-Agent `header which blocks the request and returns 403
=> F2F-92: Adding WAF rules and updating WAF association

.github/workflows/post-merge-actions-build.yml
Fixes path that was incorrect in post-merge build workflow.
Fix workflow.
- [F2F-149](https://govukverify.atlassian.net/browse/F2F-149)
=> F2F-149: Fixing path to template.yaml

src/app/cic/controllers/photoIdSelection.js, template.yaml
Added some changes in template.yaml file for pipeline to run
To run the secure pipeline
- [F2F-128](https://govukverify.atlassian.net/browse/F2F-128)
[F2F-128]: https://govukverify.atlassian.net/browse/F2F-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F- 128b 

Dockerfile
Removed unnecessary run yarn command.
=> F2F-128e: Removed run yarn command

Dockerfile
Removed unnecessary copy yarn line from dockerfile. 
Workflows weren't running successfully.
=> F2F-128f: Removed error in dockerfile.

Dockerfile, package.json
Removed part of dockerfile that
=> F2F-510: Added some dependencies and altered the dockerfile.

Dockerfile
Reverted changes to Dockerfile.
=> F2F-510a: Uncommented out changes to dockerfile.

src/locales/en/default.yml, src/locales/en/pages.yml
Fixed bugs as per tickets
https://govukverify.atlassian.net/browse/F2F-175
https://govukverify.atlassian.net/browse/F2F-177
=> [F2F-175, 177] Fixed issues as mentioned in tickets

.github/workflows/checks.yml, .gitignore, .nycrc.yml, package.json, test/browser/features/errors.feature, test/browser/pages/error.js, test/browser/pages/index.js, test/browser/pages/relying-party.js, test/browser/step_definitions/cic.js, test/browser/step_definitions/details.js, test/browser/step_definitions/errors.js, test/browser/support/env.js, test/browser/support/setup.js, test/mocks/mappings/default.json, test/mocks/mappings/session-error.json, test/utils/mocha-helpers.js
Copy across mocks and tests for basic "Unrecoverable Error page" as an initial test harness.
- [F2F-XXXX](https://govukverify.atlassian.net/browse/F2F-XXX)
=> Add browser tests

template.yaml
Added value of PrivateAPIgaetway for FE to use
FE require the value to create stack
- [F2F-152](https://govukverify.atlassian.net/browse/F2F-152)
[F2F-152]: https://govukverify.atlassian.net/browse/F2F-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-152 Added value of PrivateAPIgaetway for FE to use

src/app/cic/controllers/brpDetails.js, src/app/cic/controllers/nonUKPassportDetails.js, src/app/cic/controllers/passportDetails.js, src/app/cic/controllers/photocardDl.js, src/lib/config.js
https://govukverify.atlassian.net/browse/F2F-168 
Current date is now valid input for the pages mentioned, per the ticket.
https://user-images.githubusercontent.com/118540036/212920921-14cfede2-d42d-4405-b877-906de25c840e.mov
https://govukverify.atlassian.net/browse/F2F-180
Dates 18 months ago, inclusive of the current date, are now valid input as per the ticket.
https://user-images.githubusercontent.com/118540036/212921941-50028f76-664e-4166-8350-9e83d3a79b59.mov
=> Fixed bugs as described in tickets

src/assets/javascript/app.js
- [F2F-XXXX](https://govukverify.atlassian.net/browse/F2F-XXX)
=> Test commit

src/assets/javascript/app.js, src/locales/en/pages.yml
Added some text to landing page for visual comparison between local and build env
=> Test branch

src/app/cic/controllers/citizenCardDetails.js, src/app/cic/controllers/eeaPermanentResidencyCardDetails.js, src/app/cic/controllers/euIdentityCardDetails.js, src/app/cic/controllers/euPhotocardDlDetails.js, src/app/cic/controllers/youngScotNationalEntitlementCardDetails.js
The user input for the five new ID documents is now displayed on the summary screen
New ID types had been merged in to main after the original work was done, this adds the user input functionality from the original feature/F2F-117 branch to the 5 new ID types
- [F2F-117](https://govukverify.atlassian.net/jira/software/c/projects/F2F/boards/262?modal=detail&selectedIssue=F2F-117)
- [ x] Added screenshots to show the implementation is working
The link on the button still needs to be added
[F2F-117]: https://govukverify.atlassian.net/browse/F2F-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-117] Check Your Details Summary Screen (new ID types)

src/app/cic/controllers/eeaPermanentResidencyCardDetails.js, src/app/cic/controllers/nonUKPassportDetails.js, src/app/cic/controllers/passportDetails.js, src/app/cic/controllers/photocardDl.js, src/app/cic/controllers/youngScotNationalEntitlementCardDetails.js, src/locales/en/fields.yml
Updates the casing for chosen document type, changing some from Title Case to match the document selection screen. 
Design was updated since initial screen was published, some placeholder ID names were not properly adjusted after developing
- [F2F-197](https://govukverify.atlassian.net/browse/F2F-197)
[F2F-197]: https://govukverify.atlassian.net/browse/F2F-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-197] Check Your Details - Copy & Design Changes

template.yaml
Changed APIgateway value to match BE stack
For front end to talk to BE
- [F2F-26](https://govukverify.atlassian.net/browse/F2F-26)
[F2F-26]: https://govukverify.atlassian.net/browse/F2F-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-26 Changed APIgateway value to match BE stack

package.json, test/browser/features/HappyPath/NonUKPassport/CICCheckAnswersScreen.feature, test/browser/features/HappyPath/NonUKPassport/CICDoBEntryScreen.feature, test/browser/features/HappyPath/NonUKPassport/CICDocumentSelectionNonUKPassport.feature, test/browser/features/HappyPath/NonUKPassport/CICNameEntryScreen.feature, test/browser/features/HappyPath/NonUKPassport/CICUNonUKPassportDetails.feature, test/browser/features/HappyPath/UKPassport/CICCheckAnswersScreen.feature, test/browser/features/HappyPath/UKPassport/CICDoBEntryScreen.feature, test/browser/features/HappyPath/UKPassport/CICDocumentSelectionUKPassport.feature, test/browser/features/HappyPath/UKPassport/CICLandingPage.feature, test/browser/features/HappyPath/UKPassport/CICNameEntryScreen.feature, test/browser/features/HappyPath/UKPassport/CICUKPassportExpiryEntryScreen.feature, test/browser/pages/index.js, test/browser/pages/nonUKPassportDetailsPage.js, test/browser/step_definitions/CICDocumentSelectionNonUKPassport.step.js, test/browser/step_definitions/CICDocumentSelectionUKPassport.step.js, test/browser/step_definitions/CICNonUKPassportDetails.step.js, yarn.lock
- [F2F-209](https://govukverify.atlassian.net/browse/F2F-209)
[F2F-209]: https://govukverify.atlassian.net/browse/F2F-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F 209 Non UK Passport Happy Path

test/browser/features/HappyPath/BRP/CICCheckAnswersScreen.feature, test/browser/features/UnHappyPath/CICUKPhotoDLExpiryDtValidation.feature, test/browser/pages/index.js, test/browser/pages/photoDlDetailsPage.js, test/browser/pages/photoIdExpiryPage.js, test/browser/step_definitions/CICUKPhotoDLDateValidation.step.js
- [F2F-257](https://govukverify.atlassian.net/browse/F2F-257)
[F2F-257]: https://govukverify.atlassian.net/browse/F2F-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-257 Unhappy Path - UKPhotoDL Date Expiration

test/browser/features/BrowserBasedTests/UnHappyPath/CICUKBRPExpiryDateValidation.feature, test/browser/pages/brpDetailsPageInvalid.js, test/browser/pages/brpDetailsPageValid.js, test/browser/pages/citizenCardDetailsPage.js, test/browser/pages/euDrivingLicenceDetailsPage.js, test/browser/pages/index.js, test/browser/step_definitions/CICBRPDateValidation.step.js, test/browser/step_definitions/CICBRPDetails.step.js, test/browser/step_definitions/CICCitizenCardDetails.step.js, test/browser/step_definitions/CICDocumentSelectionBRP.step.js, test/browser/step_definitions/CICDocumentSelectionCitizenCard.step.js, test/browser/step_definitions/CICDocumentSelectionEuDrivingLicence.step.js, test/browser/step_definitions/CICDocumentSelectionUKPhotoDL.step.js, test/browser/step_definitions/CICUKPhotoDLDetails.step.js
- [F2F-258](https://govukverify.atlassian.net/browse/F2F-258)
[F2F-258]: https://govukverify.atlassian.net/browse/F2F-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-258] - BRP unhappy path automation tests passing

template.yaml
Added retention days
Pipeline was failing
- [F2F-285](https://govukverify.atlassian.net/browse/F2F-285)
[F2F-285]: https://govukverify.atlassian.net/browse/F2F-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-285 Adding retention days

test/browser/features/BrowserBasedTests/InlineValidation/CICPassportDetailsInlineErrorScreen.feature, test/browser/pages/passportDetailsPageValid.js, test/browser/step_definitions/CICPassportDetailsInlineError.step.js
- [F2F-288](https://govukverify.atlassian.net/browse/F2F-288)
[F2F-288]: https://govukverify.atlassian.net/browse/F2F-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-288  Negative test option 1

test/browser/features/BrowserBasedTests/UnHappyPath/InlineValidation/CICDoBEntryScreenInlineError.feature, test/browser/pages/dateOfBirthPage.js, test/browser/step_definitions/CICDateOfBirthEntryInlineError.step.js
- [F2F-289](https://govukverify.atlassian.net/browse/F2F-289)
[F2F-289]: https://govukverify.atlassian.net/browse/F2F-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-289 Inline error Negative test DOB screen

test/browser/features/BrowserBasedTests/UnHappyPath/BackButton/CICDocumentSelectionGoBack.feature, test/browser/features/BrowserBasedTests/UnHappyPath/InlineValidation/CICDoBEntryScreenInlineError.feature, test/browser/pages/photoIdSelectionPage.js, test/browser/step_definitions/CICDocumentSelectionReturnToLP.js
- [F2F-323](https://govukverify.atlassian.net/browse/F2F-323)
[F2F-323]: https://govukverify.atlassian.net/browse/F2F-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-323 From DS Screen Back to LP

template.yaml
Update APIGatewayId to match BE template refactor
=> Update BE Template to Reflect New Tech Design

test/browser/features/BrowserBasedTests/UnHappyPath/BackButton/CICCitizenCardDetailsGoBack.feature, test/browser/features/BrowserBasedTests/UnHappyPath/BackButton/CICDocumentSelectionGoBack.feature, test/browser/pages/citizenCardDetailsPageValid.js, test/browser/step_definitions/CICCitizenCardDetailsReturnToDS.step.js, test/browser/step_definitions/CICDocumentSelectionReturnToLP.js
- [F2F-324](https://govukverify.atlassian.net/browse/F2F-324)
[F2F-324]: https://govukverify.atlassian.net/browse/F2F-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-324 Citizen Card Expiry Date Back button test

src/app/cic/controllers/checkDetails.js, src/app/cic/controllers/checkDetails.test.js, test/mocks/mappings/claimedIdentity.json
Modifying fields in the json body to match the openapi spec [link](https://github.com/alphagov/digital-identity-architecture/blob/944216cc998acf91d46e7d5481ae52f15bbfe289/rfc/openapi/0045-claimed-identity-cri.yml#L764)
=> [F2F-122]: Aligning field names with openapi spec for claimedIdentity

test/browser/features/BrowserBasedTests/UnHappyPath/BackButton/CICNameEntryScreenGoBack.feature, test/browser/pages/nameEntryPage.js, test/browser/step_definitions/CICDocumentSelectionReturnToLP.js, test/browser/step_definitions/CICNameEntryReturnToES.step.js
- [F2F-325](https://govukverify.atlassian.net/browse/F2F-325)
[F2F-325]: https://govukverify.atlassian.net/browse/F2F-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-325 Name Entry Back button test

test/browser/features/BrowserBasedTests/UnHappyPath/BackButton/CICCheckAnswersScreenGoBack.feature, test/browser/features/BrowserBasedTests/UnHappyPath/BackButton/CICCitizenCardDetailsGoBack.feature, test/browser/features/BrowserBasedTests/UnHappyPath/BackButton/CICDoBEntryScreenGoBack.feature, test/browser/pages/checkDetailsPage.js, test/browser/step_definitions/CICCheckAnswersReturnToDoB.step.js
- [F2F-327](https://govukverify.atlassian.net/browse/F2F-327)
[F2F-327]: https://govukverify.atlassian.net/browse/F2F-327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-327 Check My Answers back button test

test/browser/features/BrowserBasedTests/UnHappyPath/ChangeButton/CICCheckAnswersExpiryDateCheckAnswer.feature, test/browser/pages/checkDetailsPage.js, test/browser/pages/index.js, test/browser/pages/nonUKPassportDetailsPageValidEdit.js, test/browser/step_definitions/CICCheckAnswersExpiryDateCheckAnswers.step.js
- [F2F-330](https://govukverify.atlassian.net/browse/F2F-330)
[F2F-330]: https://govukverify.atlassian.net/browse/F2F-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Check answers -> exp date -> check answers passing

test/browser/features/BrowserBasedTests/UnHappyPath/ChangeButton/CICCheckAnswersIDSelectionExpDateCheckAnswers.feature, test/browser/pages/checkDetailsPage.js, test/browser/pages/euDrivingLicenceDetailsPageValidEdit.js, test/browser/pages/index.js, test/browser/pages/photoIdSelectionPageEdit.js, test/browser/step_definitions/CICCheckAnswersIDSelectionExpDateCheckAnswers.step.js, test/browser/step_definitions/CICEuDrivingLicenceDetails.step.js
- [F2F-328](https://govukverify.atlassian.net/browse/F2F-328)
[F2F-328]: https://govukverify.atlassian.net/browse/F2F-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2 f 328 - Check My Answers -> ID type -> Expiry Date -> Check My Answers

package.json, test/browser/features/BrowserBasedTests/UnHappyPath/ExpiryDateValidation/CICBRPExpiryDateValidation.feature, test/browser/features/BrowserBasedTests/UnHappyPath/ExpiryDateValidation/CICCitizenCardExpiryDateValidation.feature, test/browser/features/BrowserBasedTests/UnHappyPath/ExpiryDateValidation/CICEUDrivingLicenceExpiryDateValidation.feature, test/browser/features/BrowserBasedTests/UnHappyPath/ExpiryDateValidation/CICNationalIdentityCardEEAExpiryDateValidation.feature, test/browser/features/BrowserBasedTests/UnHappyPath/ExpiryDateValidation/CICNonUKPassportDateValidation.feature, test/browser/features/BrowserBasedTests/UnHappyPath/ExpiryDateValidation/CICUKPassportExpiryDateValidationFuture.feature, test/browser/features/BrowserBasedTests/UnHappyPath/ExpiryDateValidation/CICUKPhotoDLExpiryDtValidation.feature, test/browser/features/BrowserBasedTests/UnHappyPath/ExpiryDateValidation/CICYoungScotNECExpiryDtValidation.feature, test/browser/pages/brpDetailsPageInvalid.js, test/browser/pages/citizenCardDetailsPageInvalid.js, test/browser/pages/euDrivingLicenceDetailsPageInvalid.js, test/browser/pages/nationalIdentityCardEEADetailsPageInvalid.js, test/browser/pages/nonUKPassportDetailsPageInvalid.js, test/browser/pages/passportDetailsPageInvalidFuture.js, test/browser/pages/photoDlDetailsPageInvalid.js, test/browser/pages/youngScotNECDetailsPageInvalid.js, test/browser/step_definitions/CICBRPDateValidation.step.js, test/browser/step_definitions/CICCitizenCardDateValidation.step.js, test/browser/step_definitions/CICEUDrivingLicenceDateValidation.step.js, test/browser/step_definitions/CICNationalIdentityCardEEADateValidation.step.js, test/browser/step_definitions/CICNonUKPassportDetailsDateValidation.step.js, test/browser/step_definitions/CICUKPassportDateValidationFuture.step.js, test/browser/step_definitions/CICUKPhotoDLDateValidation.step.js, test/browser/step_definitions/CICYoungScotNECDateValidation.step.js
- [F2F-369](https://govukverify.atlassian.net/browse/F2F-369)
[F2F-369]: https://govukverify.atlassian.net/browse/F2F-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2 f 369 - Re-factoring Expiry Date Validation tests, that no longer use Expiry Date screen

test/browser/features/BrowserBasedTests/UnHappyPath/ChangeButton/CICCheckAnswersDoBCheckAnswers.feature, test/browser/pages/checkDetailsPage.js, test/browser/pages/dateOfBirthPageEdit.js, test/browser/pages/index.js, test/browser/step_definitions/CICCheckAnswersDoBCheckAnswers.step.js
- [F2F-332](https://govukverify.atlassian.net/browse/F2F-332)
[F2F-332]: https://govukverify.atlassian.net/browse/F2F-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-332 - CMA -> DoB -> CMA

package.json, test/browser/features/BrowserBasedTests/PostOffice/CICLandingPagePO.feature, test/browser/pages/landingPage.js, test/browser/step_definitions/CICLandingPagePO.step.js
- [F2F-322](https://govukverify.atlassian.net/browse/F2F-322)
[F2F-322]: https://govukverify.atlassian.net/browse/F2F-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-322 Call to PO web site from F2F screens

.github/CODEOWNERS
Added codeowners file to ensure those who have permissions to review prs are limited and controlled
- [F2F-366](https://govukverify.atlassian.net/browse/F2F-366)
[F2F-366]: https://govukverify.atlassian.net/browse/F2F-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-366:Added codeowners file

template.yaml
=> Point FE to test BE stack

template.yaml
=> Updating APIGatewayID value

template.yaml
Added CSLS integration to send logs
- [F2F-442](https://govukverify.atlassian.net/browse/F2F-442)
[F2F-442]: https://govukverify.atlassian.net/browse/F2F-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F- 442 Added CSLS integration to send logs

CODEOWNERS
Removed extra codeowners file
- [F2F-445](https://govukverify.atlassian.net/browse/F2F-445)
[F2F-445]: https://govukverify.atlassian.net/browse/F2F-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-445: Removed root folder redundant CODEOWNERS file

.github/workflows/pull-request-sonar.yml, .github/workflows/sonar-analysis-on-merge.yml, sonar-project.properties
Implement sonar scan properties and workflow to run sonar scan on the di-ipv-cri-cic-front.
This includes the scan files, exclusions and code coverage.   
- [F2F-100](https://govukverify.atlassian.net/browse/F2F-100)
[F2F-100]: https://govukverify.atlassian.net/browse/F2F-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-100: Add sonar scan to ipv-cri-cic-front

template.yaml
Added custom domain, apirecord, and api mapping resources to FE repo which were previously in infra repo
To remove circular dependencies
- [F2F-580](https://govukverify.atlassian.net/browse/F2F-580)
[F2F-580]: https://govukverify.atlassian.net/browse/F2F-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-580:Added front api mapping resources 

Dockerfile
enabling debug logs by default
=> CIC: Enabling debug logs by default

template.yaml
Update API values for CIC FE 
https://govukverify.atlassian.net/browse/F2F-725
=> [CIC-725] - Update API values for CIC FE

package.json, test/browser/features/BrowserBasedTests/HappyPath/Journey/CICCheckAnswersScreen.feature, test/browser/pages/checkDetailsPage.js, test/browser/pages/dateOfBirthPage.js, test/browser/pages/dateOfBirthPageEdit.js, test/browser/pages/nameEntryPage.js, test/browser/pages/nameEntryPageEdit.js, test/browser/pages/relying-party.js, test/browser/step_definitions/CICCheckAnswers.step.js, test/browser/support/DynmoDBConnection.js, test/browser/support/shared_claim.json, yarn.lock
Implementation of :
API logic to get the url
Claim Identify Json payload
Modification of IsCurrentPage function to removed hardcoded values
To integrate API call and removing hardcoded values
- [F2F-XXXX](https://govukverify.atlassian.net/browse/F2F-XXX)
=> configuring api for front end

src/assets/scss/application.scss, src/views/cic/checkDetails.html, src/views/cic/nameEntry.html
Made alterations as per Google doc to improve accessibility and styling uniformity
https://docs.google.com/document/d/1EkADvkARX_kYl9sIjsGoMeRvJKnxOUeffUWD1SjRA8I/edit
[F2F-782](https://govukverify.atlassian.net/browse/F2F-782)
[F2F-782]: https://govukverify.atlassian.net/browse/F2F-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CIC-782- Accessibility | Improvements Post Testing

package.json, src/assets/scss/application.scss, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/cic/checkDetails.html, src/views/cic/dateOfBirth.html, src/views/cic/nameEntry.html, test/browser/step_definitions/CICCheckAnswers.step.js, yarn.lock
Changed copy and spacing according to latest Figma
- [F2F-626](https://govukverify.atlassian.net/browse/F2F-626)
[F2F-626]: https://govukverify.atlassian.net/browse/F2F-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F- 626- Copy and spacing changes

src/assets/scss/application.scss
Replaced pixel spacing value with govuk spacing integer
=> F2F-626- Replaced px with govuk value

.github/workflows/post-merge-push-test-container-to-build.yml, .github/workflows/post-merge-push-test-container-to-dev.yml
- Added workflow files for deploying into the new FE test ECRs
- [F2F-929](https://govukverify.atlassian.net/browse/F2F-929)
[F2F-929]: https://govukverify.atlassian.net/browse/F2F-929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-929: Added workflow files for FE test ECRs

.github/workflows/checks.yml, .github/workflows/pull-request-sonar.yml, package.json, test/browser/pages/checkDetailsPage.js, test/browser/pages/dateOfBirthPage.js, test/browser/pages/dateOfBirthPageEdit.js, test/browser/pages/nameEntryPage.js, test/browser/pages/nameEntryPageEdit.js
Updated npm target for executing tests to ensure the pipeline fails upon test failures
Updated page suffix for all test pages to reflect the change implemented as part of the accessibility improvements
Codebuild pipelines need to fail upon test failure
- [F2F-1042](https://govukverify.atlassian.net/browse/F2F-1042)
- [F2F-782](https://govukverify.atlassian.net/browse/F2F-782)
[F2F-1042]: https://govukverify.atlassian.net/browse/F2F-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-782]: https://govukverify.atlassian.net/browse/F2F-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> npm target updated, tests fixed with accessibility changes

src/assets/scss/application.scss, src/locales/en/default.yml, src/views/cic/enter-date-birth.html
Date of birth fieldset now has legend inside of the fieldset object so as not to impede screen readers
- [F2F-1075](https://govukverify.atlassian.net/browse/F2F-1075)
[F2F-1075]: https://govukverify.atlassian.net/browse/F2F-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CIC-1075]- | Accessibility II | Correct Element Groupings to avoid exclusion of useful information

src/locales/cy/default.yml, src/locales/cy/fields.yml, src/locales/cy/pages.errors.yml, src/locales/cy/pages.yml, src/views/cic/confirm-details.html
Introduced Welsh Translations for all the CIC pages
https://govukverify.atlassian.net/browse/KIWI-984
=> [KIWI-984] - CIC Welsh Translations

package.json, test/browser/features/BrowserBasedTests/Staging/StagingEndtoEnd.feature, test/browser/pages/index.js, test/browser/pages/orchestratorStub.js, test/browser/step_definitions/orchestratorStub.step.js, test/browser/support/AlexandraElegba.json, test/browser/support/KennethDecerquiera.json
Add Staging Tests to F2F Front End Repo
Support Removal of Red Button
- [F2F-1197](https://govukverify.atlassian.net/browse/F2F-1197)
=> Add Staging Tests to CIC FE Repo

.github/workflows/post-merge-actions-build.yml, .github/workflows/post-merge-actions-dev.yml, .secrets.baseline, Dockerfile, template.yaml
KIWI-1503 Dynatrace Integration
modified:   template.yaml
- [KIWI-1503](https://govukverify.atlassian.net/browse/KIWI-1503)
[KIWI-1503]: https://govukverify.atlassian.net/browse/KIWI-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1503 Dynatrace Integration

.github/workflows/post-merge-actions-build.yml, .github/workflows/post-merge-actions-dev.yml, .secrets.baseline, Dockerfile, template.yaml
Reverts govuk-one-login/ipv-cri-cic-front#439 as it is breaking the pipeline
=> INCIDEN-631 & INCIDEN-622 Revert "KIWI-1503 Dynatrace Integration"

.github/workflows/post-merge-actions-build.yml, .github/workflows/post-merge-actions-dev.yml, .secrets.baseline, Dockerfile, template.yaml
Revert "INCIDEN-631 & INCIDEN-622 Revert "KIWI-1503 Dynatrace Integration" (#467)"
This reverts commit 0ea827d75320cae16b9ba15b3b949ac91a8df6ac.
the modified changes are kept (the removal of the duplicated env var and removal of debug)
- [KIWI-1503](https://govukverify.atlassian.net/browse/KIWI-1503)
[KIWI-1503]: https://govukverify.atlassian.net/browse/KIWI-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "INCIDEN-631 & INCIDEN-622 Revert "KIWI-1503 Dynatrace Integration" (#467)"

test/browser/features/BrowserBasedTests/UnHappyPath/CICNameEntryScreen.feature, test/browser/pages/nameEntryPage.js, test/browser/step_definitions/CICNameEntry.step.js
Added the automated tests to verify user names length - users' names must be more than 1 character long
- [KIWI-1471](https://govukverify.atlassian.net/browse/KIWI-1471)
[KIWI-1471]: https://govukverify.atlassian.net/browse/KIWI-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI 1471 QA

.env.sample, README.md, src/app/cic/controllers/nameEntry.js, src/app/cic/controllers/root.js, src/app/cic/controllers/root.test.js, src/app/cic/fields.js, src/lib/config.js, src/locales/cy/fields.yml, src/locales/cy/pages.yml, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/cic/enter-name-photo-id.html, test/browser/features/BrowserBasedTests/UnHappyPath/CICNameEntryScreen.feature, test/browser/pages/nameEntryPage.js, test/browser/step_definitions/CICNameEntry.step.js
- Changed validation on name fields to have a min length of 2
- Call to CIC api to get journey type and use that to determine which copy to show on the name page
Required for BAV
- [KIWI-1471](https://govukverify.atlassian.net/browse/KIWI-1471)
[KIWI-1471]: https://govukverify.atlassian.net/browse/KIWI-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1471 content for no PID name question

.env.sample, README.md, src/app/cic/controllers/nameEntry.js, src/app/cic/controllers/root.js, src/app/cic/controllers/root.test.js, src/app/cic/fields.js, src/lib/config.js, src/locales/cy/fields.yml, src/locales/cy/pages.yml, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/cic/enter-name-photo-id.html
- Changed validation on name fields to have a min length of 2
- Call to CIC api to get journey type and use that to determine which copy to show on the name page
Required for BAV
- [KIWI-1471](https://govukverify.atlassian.net/browse/KIWI-1471)
[KIWI-1471]: https://govukverify.atlassian.net/browse/KIWI-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kiwi 1471 routing

package.json, src/app.js, src/lib/helmet.js, yarn.lock
Reverts govuk-one-login/ipv-cri-cic-front#402
=> KIWI-1578: Revert "chore: Update to @govuk-one-login/di-ipv-cri-common-express"

README.md, package.json, src/app.js, src/lib/helmet.js, src/locales/cy/fields.yml, src/locales/en/fields.yml, yarn.lock
Upgrade common-express to v5.0.0
Evidence post deployment to Dev: https://govukverify.atlassian.net/browse/KIWI-1587?focusedCommentId=122088
=> [KIWI-1587] - Upgrade common-express to v5.0.0

.github/workflows/checks.yml, .github/workflows/i18n.yml, .github/workflows/post-merge-actions-build.yml, .github/workflows/post-merge-actions-dev.yml, .github/workflows/post-merge-checks.yml, .github/workflows/post-merge-push-test-container-to-build.yml, .github/workflows/post-merge-push-test-container-to-dev.yml
- Updated post-merge workflow to use devplatform-upload-action-ecr@1.2.0
- Replaced individual SAM/docker steps
- Required for canary deployments across Identity
- [IPS-491](https://govukverify.atlassian.net/browse/IPS-491)
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
- Successful workflow in dev: https://github.com/govuk-one-login/ipv-cri-cic-front/actions/runs/7787142901
[IPS-491]: https://govukverify.atlassian.net/browse/IPS-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-532]: https://govukverify.atlassian.net/browse/IPS-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-495: Update post-merge workflow to use devplatform-upload-action-ecr@1.2.0

src/app.js, src/app/cic/controllers/journeyType.js
Language is now shown in the html tag as lang=en or lang=cy
To comply with the WCAG accessibility audit
- [KIWI-1547](https://govukverify.atlassian.net/browse/KIWI-1547)
[KIWI-1547]: https://govukverify.atlassian.net/browse/KIWI-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1547]- CIC | FE | Accessibility Audit | Update HTML tag to identify language

.pre-commit-config.yaml, README.md
- Updated pre-commit hooks with `pre-commit autoupdate`
- Added instructions for how to use pre-commit in readme.md
- Pre-commits to be used across Identity repos
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-486: Update pre-commit hooks and readme

package.json, test/browser/pages/dateOfBirthPage.js, test/browser/pages/dateOfBirthPageEdit.js, test/browser/pages/nameEntryPage.js, test/browser/pages/nameEntryPageEdit.js, yarn.lock
Upgrades govuk-frontend to 4.8.0 & common-express to 5.1.0 ready for new crown logo
=> [KIWI-1619] Upgrades govuk-frontend to 4.8.0

test/browser/features/BrowserBasedTests/HappyPath/Journey/CICSupportLinkScreen.feature, test/browser/pages/nameEntryPage.js, test/browser/step_definitions/CICNameEntry.step.js
Added the character Details Link in the test
To fix broken tests in F2F and NoPID
- [KIWI-1659](https://govukverify.atlassian.net/browse/KIWI-1659)
[KIWI-1659]: https://govukverify.atlassian.net/browse/KIWI-1659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1659 -Journey-independent updates to Name Entry Screen-QA

.github/workflows/post-merge-checks.yml, .github/workflows/pre-merge-checks.yml
Add missing sonar stage to pre and post merge
=> [KIWI-1770] Add missing sonar stage to pre and post merge

.github/workflows/pre-merge-checks.yml, run-tests.sh, src/app/cic/fields.js, test/browser/features/BrowserBasedTests/HappyPath/CICLanguageToggle.feature, test/browser/pages/nameEntryPage.js, test/browser/step_definitions/details.js
Add tests to validate Language Toggle
- [KIWI-1764](https://govukverify.atlassian.net/browse/KIWI-1764)
[KIWI-1764]: https://govukverify.atlassian.net/browse/KIWI-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1764 Language Toggle QA

test/browser/features/BrowserBasedTests/HappyPath/Journey/CICEndToEnd.feature, test/browser/step_definitions/CICBackendValidation.step.js, test/browser/step_definitions/CICCheckAnswers.step.js, test/browser/support/CIC_CRI_AUTH_CODE_ISSUED_SCHEMA.json, test/browser/support/CIC_CRI_END_SCHEMA.json, test/browser/support/CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json, test/browser/support/CIC_CRI_START_SCHEMA.json, test/browser/support/CIC_CRI_VC_ISSUED_SCHEMA.json, test/browser/support/TestHarness.js
Remove false positives in FE TxMA Validation Tests
- [KIWI-1773](https://govukverify.atlassian.net/browse/KIWI-1773)
[KIWI-1773]: https://govukverify.atlassian.net/browse/KIWI-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> False positives in FE TxMA Validation Tests

template.yaml
Turns on welsh toggle in staging
=> KIWI-1782: Turns on welsh toggle in staging

package.json, yarn.lock
Failing tests in pipeline
Dependencies not imported
- [KIWI-1773](https://govukverify.atlassian.net/browse/KIWI-1773)
[KIWI-1773]: https://govukverify.atlassian.net/browse/KIWI-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add ajv + ajv_formats dependencies

src/assets/scss/application.scss, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/cic/confirm-details.html, src/views/cic/enter-date-birth.html, src/views/cic/enter-name.html, test/browser/pages/checkDetailsPage.js, test/browser/pages/dateOfBirthPage.js, test/browser/pages/dateOfBirthPageEdit.js, test/browser/pages/nameEntryPage.js, test/browser/pages/nameEntryPageEdit.js
Update for DOB input validations/error messages and some small visual changes to landing page
[KIWI-1643](https://govukverify.atlassian.net/browse/KIWI-1643)
Spacing issue between names inset and details component
Spacing above button
Text change for middle names
Red side line runs across full input
Empty day/month/year
All fields empty
Invalid chars for day/month/year
Invalid number input for year
DOB in past/future
[KIWI-1643]: https://govukverify.atlassian.net/browse/KIWI-1643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1643] - CIC | FE | UCD design Review

.secrets.baseline, template.yaml
- Add new origin A record for integrating cloudFront
- Add new origin A record for integrating cloudFront
- [IPS-687](https://govukverify.atlassian.net/browse/IPS-687)
[IPS-687]: https://govukverify.atlassian.net/browse/IPS-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-687: Create DNS origin record for ClouFront

.secrets.baseline, template.yaml
- Deploy Cloudfront origin on all CIC accounts
- Previously, the cloudfront origin been deployed on dev environment
- Disabled the Web ACL association on the dev environment
- Changed include the web acl association applied on all environments
- Add DNS record on all CIC accounts
- [IPS-687](https://govukverify.atlassian.net/browse/IPS-687)
[IPS-687]: https://govukverify.atlassian.net/browse/IPS-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-687: Deploy Cloudfront Origin records all all CIC environments

README.md
PR to trigger deployment on Dev & Build
=> Fix deployment

.github/workflows/post-merge-checks.yml
This reverts commit 32992805136a75cbd374ff6d283d883654412291.
=> Revert "BAU: Bump peaceiris/actions-gh-pages from 3.9.3 to 4.0.0 (#613)"

.github/workflows/post-merge-checks.yml
This reverts commit 119886083bfa0227c634c2e735b2e17b90b4d41e.
=> Revert "BAU: Bump pre-commit/action from 3.0.0 to 3.0.1 (#610)"

package.json, yarn.lock
Reverts govuk-one-login/ipv-cri-cic-front#602
=> Revert "BAU: Bump dotenv from 16.3.1 to 16.4.5"

package.json, yarn.lock
This reverts commit a2b4a4c0ad66546e85d40c7da3943e2751c9cd3d.
=> Revert "BAU: Bump eslint-plugin-prettier from 4.2.1 to 5.1.3 (#592)"

.pre-commit-config.yaml, .secrets.baseline, src/lib/config.js, template.yaml
=> [KIWI-1852] Fix ANALYTICS_DOMAIN value

.secrets.baseline, template.yaml
Add missing IsProduction Condition
=> [KIWI-1852b] Add missing condition

template.yaml
Turns on GA4 in integration and prod. Other values are correct as per https://govukverify.atlassian.net/wiki/spaces/DID/pages/4226809994/GA+4+Package+V1.0.3+Go+No+Go+-+Kiwi
=> Turns on GA4 in integration and prod

.secrets.baseline, template.yaml
- Prepration for CloudFront Go Line
- Deploy CloudFront stacks
- DNS switchover to the CF domain name
- Disable block WAF association
- DNS switchover to the CF domain name
- Disable block WAF association
- In order for go live
- Deploy CloudFront stacks
- [IPS-784](https://govukverify.atlassian.net/browse/IPS-784)
[IPS-784]: https://govukverify.atlassian.net/browse/IPS-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-784: Deploy CloudFront on CIC production environment

.secrets.baseline, template.yaml
- Enable block WAF and associate with the load balancer
- Disable the count WAF which was deployed with the CloudFront
- Enable the block WAF 
- Associate the block with Load balancer
- Count WAF been added during CloudFront deployment.
- Having found CloudFront working, the count waf need to be disabled to enable the block WAF
- Disable the count association with Load balancer and enable the block waf association with load balancer
- Verify the CloudFront traffic using count WAF
- [IPS-740](https://govukverify.atlassian.net/browse/IPS-740)
[IPS-740]: https://govukverify.atlassian.net/browse/IPS-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-740: Enable block WAF association with Load balancer

README.md, src/app/cic/controllers/checkDetails.js, src/app/cic/controllers/checkDetails.test.js, src/app/cic/controllers/journeyType.js, src/app/cic/controllers/journeyType.test.js, src/app/cic/fields.js, src/app/cic/steps.js, src/lib/config.js, test/browser/features/BrowserBasedTests/HappyPath/Journey/CICEndToEnd.feature, test/browser/pages/checkDetailsPage.js, test/browser/pages/dateOfBirthPage.js, test/browser/pages/nameEntryPage.js, test/browser/step_definitions/CICCheckAnswers.step.js, test/browser/step_definitions/CICDateOfBirthEntryAndInlineError.step.js, test/browser/step_definitions/CICNameEntry.step.js, test/browser/step_definitions/details.js
QA changes to test logic to Separate out Screens for Existing F2F and noPID Journeys
- [KIWI-1943](https://govukverify.atlassian.net/browse/KIWI-1943)
[KIWI-1943]: https://govukverify.atlassian.net/browse/KIWI-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1943 QA Updates

README.md, src/app/cic/controllers/checkDetails.js, src/app/cic/controllers/checkDetails.test.js, src/app/cic/controllers/journeyType.js, src/app/cic/controllers/journeyType.test.js, src/app/cic/fields.js, src/app/cic/steps.js, src/lib/config.js, src/views/cic/confirm-details-no-photo-id.html, src/views/cic/enter-date-birth-no-photo-id.html, src/views/cic/enter-name-no-photo-id.html, test/browser/features/BrowserBasedTests/HappyPath/Journey/CICEndToEnd.feature, test/browser/pages/checkDetailsPage.js, test/browser/pages/dateOfBirthPage.js, test/browser/pages/nameEntryPage.js, test/browser/step_definitions/CICCheckAnswers.step.js, test/browser/step_definitions/CICDateOfBirthEntryAndInlineError.step.js, test/browser/step_definitions/CICNameEntry.step.js, test/browser/step_definitions/details.js
Built name entry, date of birth entry and check details screens for no photo ID journey, removed existing conditional copy rendering
To increase maintainability and quality of code as more use cases for CIC are adopted
- [KIWI-1943](https://govukverify.atlassian.net/browse/KIWI-1943)
[KIWI-1943]: https://govukverify.atlassian.net/browse/KIWI-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1943] - CIC | FE | Separate out Screens for Existing F2F and noPID Journeys

test/browser/features/BrowserBasedTests/HappyPath/Journey/CICEndToEnd.feature, test/browser/support/CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json, test/browser/support/CIC_CRI_START_SCHEMA.json
Updates to QA logic + E2E tests to reflect journeyType changes made as part of KIWI-1963
- [KIWI-1963](https://govukverify.atlassian.net/browse/KIWI-1963)
[KIWI-1963]: https://govukverify.atlassian.net/browse/KIWI-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1963 QA

test/browser/support/CIC_CRI_START_BANK_ACCOUNT_SCHEMA.json, test/browser/support/CIC_CRI_START_LOW_CONFIDENCE_SCHEMA.json, test/browser/support/CIC_CRI_START_SCHEMA.json
Update JSON Schema for TxMA checks 
- [KIWI-1963](https://govukverify.atlassian.net/browse/KIWI-1963)
[KIWI-1963]: https://govukverify.atlassian.net/browse/KIWI-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1963 Test Fix

.secrets.baseline, template.yaml
- Add CIC CRI alarms to the pager duty topic. This will publish on the topic when the alarm is triggered and pager duty will be triggered.
- Add CIC CRI alarms to the pager duty topic to publish the topic
- Add CIC CRI alarms to the pager duty topic to publish the topic
- [IPS-1181](https://govukverify.atlassian.net/browse/IPS-1181)
[IPS-1181]: https://govukverify.atlassian.net/browse/IPS-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1181: Subscribe CIC CRI alarms to the pager duty topic

package.json, yarn.lock
=> Update govuk-frontend from v4.8.0 to v4.9.0.

.github/workflows/aws-sus-scanner.yml
- Workflow on PR for Sustainability scan
- add comments in PR the scan outcome
- enforce infrastructure-as-code to identify sustainability best practices
- [IPS-1395](https://govukverify.atlassian.net/browse/IPS-1395)
[IPS-1395]: https://govukverify.atlassian.net/browse/IPS-1395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1395 add aws sus scanner workflow

.secrets.baseline, package.json, src/app.js, template.yaml
Added FE Vital Signs logging to track values that inform Capacity Management work
=> KIWI-2011 - Implementing FE Vital Signs Logging

.secrets.baseline, Dockerfile, template.yaml
- Configured AWS ECS healthchecks in template
- Updated Dockerfile to reference healthcheck
=> KIWI-2017 - Configuring ECS Healthchecks

.github/workflows/pre-merge-checks.yml, package.json, test/browser/pages/nameEntryPage.js
Remove logging added to isCurrentPage function
Logging added to provide more info around failing pipeline tests and incorrectly merged to main 
=> Remove logging added to isCurrentPage function

package.json, src/app/cic/controllers/checkDetails.js, src/app/cic/controllers/checkDetails.test.js, src/app/cic/controllers/journeyType.js, src/app/cic/controllers/journeyType.test.js, test/utils/mocha-helpers.js, yarn.lock
Add missing createPersonalDataHeaders function to required controllers
This was mistakenly omitted and should have been implemented at the same time as the other CRI's, see related F2F ticket here https://govukverify.atlassian.net/browse/KIWI-1787
=> Add missing createPersonalDataHeaders function to required controllers

template.yaml
Switched on the Rebrand feature flag in Production
Introducing brand changes
- [KIWI-2374](https://govukverify.atlassian.net/browse/KIWI-2374)
[KIWI-2374]: https://govukverify.atlassian.net/browse/KIWI-2374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2374] - CIC | Enable the Rebrand feature flag in Production 
